power <- read.csv("household_power_consumption.txt", sep=";", header=TRUE)
df <- power[power$Date=="1/2/2007" | power$Date=="2/2/2007",]
#df$Date <- as.character(df[,1])
#df$Time <- as.character(df[,2])
df$DateTime <- strptime(paste(df$Date, df$Time), "%d/%m/%Y %H:%M:%S")
df[,3] <- as.numeric(as.character(df[,3]))
df[,4] <- as.numeric(as.character(df[,4]))
df[,5] <- as.numeric(as.character(df[,5]))
df[,6] <- as.numeric(as.character(df[,6]))
df[,7] <- as.numeric(as.character(df[,7]))
df[,8] <- as.numeric(as.character(df[,8]))
df[,9] <- as.numeric(as.character(df[,9]))

png("plot4.png", height=480, width=480)
par(mfrow=c(2,2))
plot(df$DateTime, df$Global_active_power, xlab="DateTime", ylab="Global Active Power", type="l")
plot(df$DateTime, df$Voltage, xlab="datetime", ylab="Voltage", type="l")
plot(df$DateTime, df$Global_active_power, xlab=NA, ylab="Energy sub metering", ylim=range(0:40), type="n")
lines(df$DateTime, df$Sub_metering_1, col="black")
lines(df$DateTime, df$Sub_metering_2, col="red")
lines(df$DateTime, df$Sub_metering_3, col="blue")
legend("topright", lty=c(1,1,1,1), col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(df$DateTime, df$Global_reactive_power, xlab="datetime", ylab="Global_reactive_power", type="l")
dev.off()
